minimumReleaseAgeExclude:
  - '@scriptc/cli-darwin-arm64@0.2.6'
  - '@scriptc/cli-darwin-x64@0.2.6'
  - '@scriptc/cli-linux-arm64-gnu@0.2.6'
  - '@scriptc/cli-linux-arm64-musl@0.2.6'
  - '@scriptc/cli-linux-x64-gnu@0.2.6'
  - '@scriptc/cli-linux-x64-musl@0.2.6'
  - '@scriptc/cli-win32-x64-msvc@0.2.6'
  - '@scriptc/compiler@0.2.6'
  - '@scriptc/llvm-darwin-arm64@0.2.6'
  - '@scriptc/llvm-darwin-x64@0.2.6'
  - '@scriptc/llvm-linux-arm64-gnu@0.2.6'
  - '@scriptc/llvm-linux-arm64-musl@0.2.6'
  - '@scriptc/llvm-linux-x64-gnu@0.2.6'
  - '@scriptc/llvm-linux-x64-musl@0.2.6'
  - '@scriptc/llvm-win32-x64-msvc@0.2.6'
  - '@scriptc/runtime-android-arm64@0.2.6'
  - '@scriptc/runtime-darwin-arm64@0.2.6'
  - '@scriptc/runtime-darwin-x64@0.2.6'
  - '@scriptc/runtime-ios-arm64@0.2.6'
  - '@scriptc/runtime-ios-simulator-arm64@0.2.6'
  - '@scriptc/runtime-linux-arm64-gnu@0.2.6'
  - '@scriptc/runtime-linux-x64-gnu@0.2.6'
  - '@scriptc/runtime-wasm32-wasi@0.2.6'
  - '@scriptc/runtime@0.2.6'
  - scriptc@0.2.6
